### ISSUE TITLE
Implement a testing framework

### ISSUE THREAD

**Issue by SillySalamndr** [Imaginary-Horizons-Productions/HorizonsBot#141] opened 2024-01-11 03:55 UTC
Since this bot is largely finished and well tested, this would be a good place to make a first pass at one or more testing frameworks. Our goals are:

1. Implement the desired testing framework(s).
1. Port the basic templating to the bot template.

**Comment by ntseng** [comment] 2024-02-10 05:46
Closing as duplicate of https://github.com/Imaginary-Horizons-Productions/Discord-Bot-Template/issues/25

**Closed as completed by ntseng** 2024-02-10 05:46 UTC
Labels: type: internal doc, type: dev tool, type: refactor
